twig:
  form_themes:
    - '@IbexaFormattedTextLine/form_theme.html.twig'

ezpublish:
  system:
    default:
      fielddefinition_edit_templates:
        - { template: "@ezdesign/fieldtype/maskedtextline_definition_edit.html.twig", priority: 1 }
