twig:
  form_themes:
    - '@IbexaFormattedTextLine/form_theme.html.twig'

ibexa:
  system:
    default:
      fielddefinition_edit_templates:
        - { template: "@ibexadesign/fieldtype/maskedtextline_definition_edit.html.twig", priority: 1 }
