services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  adamwojs.ibexa_formatted_textline.search.elasticsearch.query.common.aggregation_visitor.field.formatted_textline_term:
    class: Ibexa\Elasticsearch\Query\AggregationVisitor\TermAggregationVisitor
    factory: ['@Ibexa\Elasticsearch\Query\AggregationVisitor\Factory\SearchFieldAggregationVisitorFactory', 'createTermAggregationVisitor']
    arguments:
      $aggregationClass: 'AdamWojs\IbexaFormattedTextLineBundle\Search\Query\Aggregation\FormattedTextLineTermAggregation'
      $searchIndexFieldName: 'value'
    tags:
      - { name: ibexa.search.elasticsearch.query.content.aggregation.visitor }
      - { name: ibexa.search.elasticsearch.query.location.aggregation.visitor }

  adamwojs.ibexa_formatted_textline.search.elasticsearch.query.common.aggregation_result_extractor.field.formatted_textline_term:
    class: Ibexa\Elasticsearch\Query\ResultExtractor\AggregationResultExtractor\TermAggregationResultExtractor
    arguments:
      $aggregationClass: 'AdamWojs\IbexaFormattedTextLineBundle\Search\Query\Aggregation\FormattedTextLineTermAggregation'
    tags:
      - { name: ibexa.search.elasticsearch.query.content.aggregation.result.extractor }
      - { name: ibexa.search.elasticsearch.query.location.aggregation.result.extractor }

