services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  ezplatform.search.solr.query.common.aggregation_visitor.field.formatted_textline_term:
    class: EzSystems\EzPlatformSolrSearchEngine\Query\Common\AggregationVisitor\TermAggregationVisitor
    factory: ['@EzSystems\EzPlatformSolrSearchEngine\Query\Common\AggregationVisitor\Factory\ContentFieldAggregationVisitorFactory', 'createTermAggregationVisitor']
    arguments:
      $aggregationClass: 'AdamWojs\IbexaFormattedTextLineBundle\Search\Query\Aggregation\FormattedTextLineTermAggregation'
      $searchIndexFieldName: 'value'
    tags:
      - { name: ezplatform.search.solr.query.content.aggregation_visitor }
      - { name: ezplatform.search.solr.query.location.aggregation_visitor }

  ezplatform.search.solr.query.common.aggregation_result_extractor.field.formatted_textline_term:
    class: EzSystems\EzPlatformSolrSearchEngine\ResultExtractor\AggregationResultExtractor\TermAggregationResultExtractor
    arguments:
      $aggregationClass: 'AdamWojs\IbexaFormattedTextLineBundle\Search\Query\Aggregation\FormattedTextLineTermAggregation'
    tags:
      - { name: ezplatform.search.solr.query.content.aggregation_result_extractor }
      - { name: ezplatform.search.solr.query.location.aggregation_result_extractor }
